baseURL = "https://ryddedagen.no"
languageCode = "nb"
defaultContentLanguage = "nb"
title = "ryddedagen.no"

[markup.goldmark.renderer]
unsafe = true

# Introsiden til årlig revisjon har ingen egen innholdsfil-oppføring i menyen
[[menu.main]]
  name = "Hva er årlig revisjon?"
  url = "/arlig-revisjon/"
  weight = 1
